name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tests:
    name: Unit tests & Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: supercharged_dart_plus / get dependencies & test
        run: |
          flutter pub get
          flutter analyze
          flutter test
        working-directory: ./supercharged_dart_plus

      - name: supercharged_plus / get dependencies & test
        run: |
          flutter pub get
          flutter analyze
          flutter test
        working-directory: ./supercharged_plus
